#! /usr/bin/env python

import json
from datetime import datetime

def main():

    print(json.dumps({
        'version': datetime.isoformat(datetime.now())
    }))

if __name__ == '__main__':
    main()
